name: profmate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  fl_chart: ^0.66.0
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0
  flutter_localizations:
    sdk: flutter
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.1.2
  flutter_speed_dial: ^7.0.0
  mask_text_input_formatter: ^2.4.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  font_awesome_flutter: ^10.9.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/